name: Ash Davies
title: Ash Davies
description: "Google Developer Expert for Android, Senior Engineer at Immobilienscout24, Kotlin enthusiast, Flutter amateur, digital policy advocate, musing over British tea and Salt & Vinegar crisps"
url: "https://ashdavies.io/"

github_username:  ashdavies
twitter_username: askashdavies
linkedin_username: ashowendavies
stack_of_username: 571416
medium_username:  ashdavies

avatar: yes
avatar_img_path: "imgs/gde-badge-final.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.svg"

markdown: kramdown
permalink: pretty
