name: Ash Davies
title: Ash Davies
description: "Twenty-something Android Developer living in Berlin,<br />musing over fond memories of British tea and Salt & Vinegar crisps"
url: "http://ashdavies.io/"

github_username:  ashdavies
twitter_username: _ashdavies
google_plus_username: AshDavies
linkedin_username: ashowendavies
stack_of_username: 571416
medium_username:  ashdavies

avatar: yes
avatar_img_path: "imgs/ybCMyrp6.jpg"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.svg"

markdown: kramdown
permalink: pretty
